#!/bin/bash
################################################################################
# File: pre-push
#
# Author: Benjamin Johnson
#
# Date Created: Saturday November 1, 2014
# Date Revised: N/A
#
# Description: pre-push git hook
################################################################################

#
#
#

















# End pre-push
